version: 2
jobs:
  build:
    working_directory: /go/src/github.com/utilitywarehouse/app
    docker:
    - image: circleci/golang:1
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run: mv /go/src/github.com/utilitywarehouse/app /go/src/github.com/utilitywarehouse/$CIRCLE_PROJECT_REPONAME
      - run: git config --global url."https://$GITHUB_TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - run: cd ../$CIRCLE_PROJECT_REPONAME && make ci-docker-build

workflows:
  version: 2
  development:
    jobs:
      - build
